# Generated by Django 5.0.6 on 2024-05-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordereditem_owner_alter_ordereditem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
